-- ============================================================================
-- Diagnóstico: qué falta en la base respecto a las migraciones del repositorio
-- ============================================================================
-- Solo lectura: no cambia nada. Pégala en el SQL Editor de Supabase.
--
-- La lista sale de aplicar TODAS las migraciones de supabase/migrations/ en
-- una base vacía (probar-migraciones.sh) y anotar lo que queda en el esquema
-- public. Cada fila del resultado es algo que el código espera y la base no
-- tiene: una migración sin aplicar. Sin filas, la base está al día.
--
-- No mira columnas: si falta una columna, el error de la pantalla dice cuál.
-- Al añadir migraciones con funciones o tablas nuevas, añádelas aquí.
-- ============================================================================

WITH esperado(tipo, nombre) AS (VALUES
  ('función', 'anular_factura(uuid,uuid,text)'),
  ('función', 'auditoria_autor()'),
  ('función', 'auditoria_enmascarar(jsonb)'),
  ('función', 'auditoria_identificador(oid,jsonb)'),
  ('función', 'auditoria_inmutable()'),
  ('función', 'auditoria_registrar()'),
  ('función', 'auditoria_verificar()'),
  ('función', 'banco_conciliar(uuid,uuid,uuid,text)'),
  ('función', 'banco_desconciliar(uuid,uuid)'),
  ('función', 'borrar_cobro(uuid)'),
  ('función', 'caja_movimiento_congelar()'),
  ('función', 'carpeta_uuid(text)'),
  ('función', 'cobro_web_al_dia(uuid)'),
  ('función', 'compra_registrada_inmutable()'),
  ('función', 'confirmar_presupuesto(uuid)'),
  ('función', 'coste_metro_empresa(uuid)'),
  ('función', 'emitir_factura(uuid,uuid,jsonb,jsonb,date,date,uuid,uuid,text,uuid,text,boolean,uuid)'),
  ('función', 'emitir_factura_textil(uuid,jsonb,jsonb,uuid,date,date,uuid,uuid,text,uuid,text,boolean,uuid,uuid)'),
  ('función', 'empresa_global_replicar()'),
  ('función', 'empresa_por_defecto()'),
  ('función', 'empresa_serie(uuid,factura_tipo)'),
  ('función', 'es_miembro_empresa(uuid,uuid)'),
  ('función', 'factura_calcular(jsonb)'),
  ('función', 'factura_cambiar_estado_cobro(uuid,uuid,factura_estado)'),
  ('función', 'factura_comprobar_fecha(uuid,text,integer,date)'),
  ('función', 'factura_emitida_no_se_borra()'),
  ('función', 'factura_inmutable()'),
  ('función', 'factura_item_inmutable()'),
  ('función', 'factura_referencia(text,integer,integer)'),
  ('función', 'facturas_huecos_en_serie()'),
  ('función', 'handle_new_user()'),
  ('función', 'has_role(uuid,app_role)'),
  ('función', 'hook_password_verification_attempt(jsonb)'),
  ('función', 'inversion_congelar()'),
  ('función', 'is_tienda_member(uuid,uuid)'),
  ('función', 'pedido_borrar_cobros_automaticos()'),
  ('función', 'pedido_cobro_web()'),
  ('función', 'pedido_coste_congelado()'),
  ('función', 'pedido_devolucion_cobro_web()'),
  ('función', 'pedido_estado_a_envio(pedido_estado,estado_envio)'),
  ('función', 'pedido_estado_a_pago(pedido_estado,estado_pago)'),
  ('función', 'pedido_estado_a_produccion(pedido_estado,estado_produccion)'),
  ('función', 'pedido_item_coste_congelado()'),
  ('función', 'pedido_sincronizar_estados()'),
  ('función', 'plantillas_correo_sembrar(uuid)'),
  ('función', 'presupuesto_visible(uuid)'),
  ('función', 'producto_visible(uuid,uuid)'),
  ('función', 'referencia_documento(text,integer,integer)'),
  ('función', 'registrar_cobro(uuid,uuid,date,numeric,cobro_metodo,boolean,uuid,text)'),
  ('función', 'rls_auto_enable()'),
  ('función', 'serie_estado(uuid,integer)'),
  ('función', 'serie_fijar_inicio(uuid,uuid,integer,factura_tipo,integer)'),
  ('función', 'siguiente_numero(uuid,text,integer)'),
  ('función', 'smtp_borrar_tienda(uuid)'),
  ('función', 'smtp_estado(uuid)'),
  ('función', 'smtp_guardar(uuid,uuid,text,integer,text,text)'),
  ('función', 'smtp_leer(uuid)'),
  ('función', 'stock_aplicar_movimiento()'),
  ('función', 'stock_cantidad_solo_por_movimiento()'),
  ('función', 'stock_descuadres()'),
  ('función', 'stock_movimiento_inmutable()'),
  ('función', 'stock_recalcular_reservado()'),
  ('función', 'stock_reservas_descuadres()'),
  ('función', 'textil_compra_registrar(uuid)'),
  ('función', 'textil_factura_inmutable()'),
  ('función', 'textil_factura_item_inmutable()'),
  ('función', 'textil_pedido_entregar(uuid)'),
  ('función', 'textil_stock_retirar(uuid)'),
  ('función', 'ticket_receptor(uuid,jsonb,uuid,numeric)'),
  ('función', 'tienda_borrado_permitido()'),
  ('función', 'tienda_credenciales_guardar(uuid,text,text)'),
  ('función', 'tienda_credenciales_leer(uuid)'),
  ('función', 'tienda_resumen_borrado(uuid)'),
  ('función', 'tiendas_sembrar_plantillas()'),
  ('función', 'touch_updated_at()'),
  ('tabla', 'auditoria'),
  ('tabla', 'auth_intentos_fallidos_login'),
  ('tabla', 'banco_conciliaciones'),
  ('tabla', 'banco_movimientos'),
  ('tabla', 'caja_conceptos'),
  ('tabla', 'caja_movimientos'),
  ('tabla', 'caja_socios'),
  ('tabla', 'cliente_tiendas'),
  ('tabla', 'clientes'),
  ('tabla', 'clientes_duplicados_por_email'),
  ('tabla', 'clientes_posibles_duplicados'),
  ('tabla', 'cobros'),
  ('tabla', 'contadores'),
  ('tabla', 'empresa_global'),
  ('tabla', 'empresas'),
  ('tabla', 'enlaces_seguimiento'),
  ('tabla', 'factura_items'),
  ('tabla', 'facturas'),
  ('tabla', 'gerencia_ajustes'),
  ('tabla', 'gerencia_gastos_fijos'),
  ('tabla', 'gerencia_objetivos'),
  ('tabla', 'inversion_movimientos'),
  ('tabla', 'pedido_correos_enviados'),
  ('tabla', 'pedido_devoluciones'),
  ('tabla', 'pedido_items'),
  ('tabla', 'pedidos'),
  ('tabla', 'pedidos_pendientes_cobro'),
  ('tabla', 'presupuesto_items'),
  ('tabla', 'presupuestos'),
  ('tabla', 'productos'),
  ('tabla', 'profiles'),
  ('tabla', 'series_facturacion'),
  ('tabla', 'smtp_config'),
  ('tabla', 'textil_clientes'),
  ('tabla', 'textil_cobros'),
  ('tabla', 'textil_compra_lineas'),
  ('tabla', 'textil_compras'),
  ('tabla', 'textil_factura_items'),
  ('tabla', 'textil_facturas'),
  ('tabla', 'textil_marcas'),
  ('tabla', 'textil_pedido_items'),
  ('tabla', 'textil_pedidos'),
  ('tabla', 'textil_presupuesto_items'),
  ('tabla', 'textil_presupuestos'),
  ('tabla', 'textil_stock'),
  ('tabla', 'textil_stock_movimientos'),
  ('tabla', 'textil_stock_reservas'),
  ('tabla', 'tienda_credenciales'),
  ('tabla', 'tienda_plantillas_correo'),
  ('tabla', 'tienda_seguimiento_config'),
  ('tabla', 'tienda_usuarios'),
  ('tabla', 'tiendas'),
  ('tabla', 'user_roles')
)
SELECT tipo, nombre AS falta
  FROM esperado
 WHERE (tipo = 'función' AND to_regprocedure('public.' || nombre) IS NULL)
    OR (tipo = 'tabla' AND to_regclass('public.' || nombre) IS NULL)
 ORDER BY tipo, nombre;
