/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelFacturacionGlobalRouteImport } from './routes/panel/facturacion-global'
import { Route as PanelTiendasIndexRouteImport } from './routes/panel/tiendas/index'
import { Route as PanelTiendasTiendaIdRouteRouteImport } from './routes/panel/tiendas/$tiendaId/route'
import { Route as PanelTiendasTiendaIdIndexRouteImport } from './routes/panel/tiendas/$tiendaId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelFacturacionGlobalRoute = PanelFacturacionGlobalRouteImport.update({
  id: '/facturacion-global',
  path: '/facturacion-global',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelTiendasIndexRoute = PanelTiendasIndexRouteImport.update({
  id: '/tiendas/',
  path: '/tiendas/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelTiendasTiendaIdRouteRoute =
  PanelTiendasTiendaIdRouteRouteImport.update({
    id: '/tiendas/$tiendaId',
    path: '/tiendas/$tiendaId',
    getParentRoute: () => PanelRouteRoute,
  } as any)
const PanelTiendasTiendaIdIndexRoute =
  PanelTiendasTiendaIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelTiendasTiendaIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/panel/facturacion-global': typeof PanelFacturacionGlobalRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/tiendas/$tiendaId': typeof PanelTiendasTiendaIdRouteRouteWithChildren
  '/panel/tiendas/': typeof PanelTiendasIndexRoute
  '/panel/tiendas/$tiendaId/': typeof PanelTiendasTiendaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel/facturacion-global': typeof PanelFacturacionGlobalRoute
  '/panel': typeof PanelIndexRoute
  '/panel/tiendas': typeof PanelTiendasIndexRoute
  '/panel/tiendas/$tiendaId': typeof PanelTiendasTiendaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/panel/facturacion-global': typeof PanelFacturacionGlobalRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/tiendas/$tiendaId': typeof PanelTiendasTiendaIdRouteRouteWithChildren
  '/panel/tiendas/': typeof PanelTiendasIndexRoute
  '/panel/tiendas/$tiendaId/': typeof PanelTiendasTiendaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/auth'
    | '/panel/facturacion-global'
    | '/panel/'
    | '/panel/tiendas/$tiendaId'
    | '/panel/tiendas/'
    | '/panel/tiendas/$tiendaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/panel/facturacion-global'
    | '/panel'
    | '/panel/tiendas'
    | '/panel/tiendas/$tiendaId'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/auth'
    | '/panel/facturacion-global'
    | '/panel/'
    | '/panel/tiendas/$tiendaId'
    | '/panel/tiendas/'
    | '/panel/tiendas/$tiendaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/facturacion-global': {
      id: '/panel/facturacion-global'
      path: '/facturacion-global'
      fullPath: '/panel/facturacion-global'
      preLoaderRoute: typeof PanelFacturacionGlobalRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/tiendas/': {
      id: '/panel/tiendas/'
      path: '/tiendas'
      fullPath: '/panel/tiendas/'
      preLoaderRoute: typeof PanelTiendasIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/tiendas/$tiendaId': {
      id: '/panel/tiendas/$tiendaId'
      path: '/tiendas/$tiendaId'
      fullPath: '/panel/tiendas/$tiendaId'
      preLoaderRoute: typeof PanelTiendasTiendaIdRouteRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/tiendas/$tiendaId/': {
      id: '/panel/tiendas/$tiendaId/'
      path: '/'
      fullPath: '/panel/tiendas/$tiendaId/'
      preLoaderRoute: typeof PanelTiendasTiendaIdIndexRouteImport
      parentRoute: typeof PanelTiendasTiendaIdRouteRoute
    }
  }
}

interface PanelTiendasTiendaIdRouteRouteChildren {
  PanelTiendasTiendaIdIndexRoute: typeof PanelTiendasTiendaIdIndexRoute
}

const PanelTiendasTiendaIdRouteRouteChildren: PanelTiendasTiendaIdRouteRouteChildren =
  {
    PanelTiendasTiendaIdIndexRoute: PanelTiendasTiendaIdIndexRoute,
  }

const PanelTiendasTiendaIdRouteRouteWithChildren =
  PanelTiendasTiendaIdRouteRoute._addFileChildren(
    PanelTiendasTiendaIdRouteRouteChildren,
  )

interface PanelRouteRouteChildren {
  PanelFacturacionGlobalRoute: typeof PanelFacturacionGlobalRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelTiendasTiendaIdRouteRoute: typeof PanelTiendasTiendaIdRouteRouteWithChildren
  PanelTiendasIndexRoute: typeof PanelTiendasIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelFacturacionGlobalRoute: PanelFacturacionGlobalRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelTiendasTiendaIdRouteRoute: PanelTiendasTiendaIdRouteRouteWithChildren,
  PanelTiendasIndexRoute: PanelTiendasIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
