// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkkqinvuxylsvxojgxov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBra3FpbnZ1eHlsc3Z4b2pneG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1Mjc5OTQsImV4cCI6MjA5NzEwMzk5NH0.dOTae2K0uAHNa7Q2z21jXMqHpDXGwxyb2FmQa3ggDw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});